### ISSUE TITLE
more data architecture support, thx

### ISSUE THREAD

**Issue by userpj** [B777B2056/FoxbatDB#2]
thx

**Comment by B777B2056** [comment]
The conclusion is that we are not currently planning to support complex redis-like structures, but we may add support for semi-structured data such as JSON and XML.
On the one hand, the implementation is more complicated (for example, to support commands such as LPUSH, a linked list needs to be maintained on the disk; but the Set and Zset structures are difficult to maintain on the disk, and only one copy of the field can be maintained in the memory, which will cause the program's memory usage to increase) , but I don’t have much energy;
On the other hand, structures such as Zset may cause various problems when distributed support is added in the future.
